name: Deploy To EC2

on:
  push:
    branches:
      - yunseopdev

env:
  BASE_RESOURCE_PATH: ./src/main/resources/application.yml

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      # 잘 실행되는지 확인하는 코드를 넣어도 좋음
#      - name: Test
#      run: |
#        ls
#        pwd

      - name: JDK 17버전 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: application.yml 파일 만들기
#        uses: microsoft/variable-substitution@v1
#        with:
#          files: ${{ env.BASE_RESOURCE_PATH }}
#        env:
#          spring.security.oauth2.client.registration.google.client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
#          spring.security.oauth2.client.registration.google.client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      #오류가 발생하면 이 코드를 추가할 수도 있음
      - name: gradlew에 실행 권한 부여하기
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드하기
        run: ./gradlew clean build

      - name: 빌드된 파일 이름 변경하기
        run: mv ./build/libs/*SNAPSHOT.jar ./project.jar

      - name: SCP로 EC2에 빌드된 파일 전송하기
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: project.jar
          target: /home/ubuntu/cicd-server/tobe
          #tobe 폴더에 project.jar파일 넣음

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/cicd-server/current   #새로운 업데이트를 위해 기존의 jar파일이 있는 current폴더를 삭제함
            mkdir /home/ubuntu/cicd-server/current  #현재 실행중인 프로젝트에 대한 코드를 current폴더에 넣어둠
            mv /home/ubuntu/cicd-server/tobe/project.jar /home/ubuntu/cicd-server/current/project.jar #tobe폴더의 값을 current폴더로 옮김
            cd /home/ubuntu/cicd-server/current
            sudo fuser -k -n tcp 8080 || true     #프로젝트 실행하고 있으면 안되기 때문에 서버를 꺼주기
            nohup java -jar project.jar > ./output.log 2>&1 & 
            rm -rf /home/ubuntu/cicd-server/tobe  #필요없어진 tobe폴더 삭제하기